server:
  port: 8081
  compression:
    enabled: false
    http2:
      enabled: false
    servlet:
      session:
        timeout: 30m
    tomcat:
      use-relative-redirects: true
spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/User
    username: ivalov
    password: 059937
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true